image: comp1531/automarking:latest

stages:
  - checks

before_script:
  - echo 'Installing dependencies'
  - npm install

testing:
  stage: checks
  only:
    - master
    - merge_requests
  script:
    - echo "Running tests"
    - npm install
    - SERVER_LOG=$(mktemp)

    # # Start server in background and capture output in temp file
    - npm start &> $SERVER_LOG & pid=$!
    - sleep 2
    - ps -o pid | egrep -q "^\s*${pid}$" || (cat $SERVER_LOG && exit 1)

    # # Run test then kill server
    - npm test || (cat $SERVER_LOG && exit 1)
    - sleep 1
    - kill -SIGINT %1

    - cat $SERVER_LOG

    - npm test

linting:
  stage: checks
  only:
    - master
    - merge_requests
  script:
    - echo 'Running linters'
    - npm run lint
